### ISSUE TITLE
Error running on rhel 7 with default parameter

### ISSUE THREAD

**Issue by venki3v** [rji/puppet-jboss_as#12]
Error: Failed to apply catalog: Could not find dependency File[/etc/init.d/jboss-as] for Exec[install_service] at /etc/puppet/modules/jboss_as/manifests/install.pp:105

**Comment by rji** [comment]
The README states that this has only been tested on CentOS 6 and Ubuntu 12.04. EL 7 uses systemd, so I wouldn't expect `/etc/init.d` to exist, which is probably leading to the failure you mentioned.

I no longer use JBoss (and as a result don't really maintain this module anymore), and don't have any plans to implement RHEL 7 support. As always, pull requests are always welcome :smile:
